name: flutter_ui_challenges
description: A new flutter module project.

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  # This section identifies your Flutter project as a module meant for
  # embedding in a native host app.  These identifiers should _not_ ordinarily
  # be changed after generation - they are used to ensure that the tooling can
  # maintain consistency when adding or modifying assets and plugins.
  # They also do not have any bearing on your native host application's
  # identifiers, which may be completely independent or the same as these.
  module:
    androidX: true
    androidPackage: com.example.flutter_ui_challenges
    iosBundleIdentifier: com.example.flutterUiChallenges

  assets:
    - assets/images/base/
    - assets/images/login_form/
    - assets/images/onboarding/
    - assets/images/page_view/
    - assets/images/furniture/
    - assets/images/members/
    - assets/images/paddock/
    - assets/images/carousel/
    - assets/images/despicable_me/
    - assets/images/formula_1/
    - assets/images/page_reveal/
    - assets/images/page_transition/
    - assets/images/story_app/
    - assets/images/video_game/
    - assets/images/bank_card/
    - assets/images/weather_forecast/
    - assets/images/space_travel_ui/

  fonts:
    - family: SF-Pro-Text-Regular
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Regular.otf

    - family: SF-Pro-Text-Bold
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Bold.otf

    - family: Calibre-Semibold
      fonts:
        - asset: assets/fonts/Calibre Semibold.otf

    - family: Montserrat-Bold
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf

    - family: Montserrat-Black
      fonts:
        - asset: assets/fonts/Montserrat-Black.ttf

    - family: Montserrat-Medium
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
    - family: SF-Pro-Display-Bold
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Bold.ttf

    - family: SF-Pro-Display-Regular
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.ttf

    - family: Roboto-Light
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf

    - family: mermaid
      fonts:
        - asset: assets/fonts/Mermaid1001.ttf

    - family: BebasNeue
      fonts:
        - asset: assets/fonts/BebasNeue-Regular.ttf

    - family: PTM55FT
      fonts:
        - asset: assets/fonts/PTM55FT.ttf

    - family: DroidSans
      fonts:
        - asset: assets/fonts/Droid-Sans-Fallback/DroidSans.ttf

    - family: Flamante-Roma
      fonts:
        - asset: assets/fonts/Flamante-Roma-Medium.ttf

    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf
        - asset: assets/fonts/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/WorkSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/WorkSans-Bold.ttf
          weight: 700

    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/playfair_display/PlayfairDisplay-Regular.ttf
        - asset: assets/fonts/playfair_display/PlayfairDisplay-RegularItalic.ttf
          style: italic

        - asset: assets/fonts/playfair_display/PlayfairDisplay-Bold.ttf
          weight: 700

        - asset: assets/fonts/playfair_display/PlayfairDisplay-BoldItalic.ttf
          weight: 700
          style: italic

    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu/Ubuntu-Regular.ttf
        - asset: assets/fonts/Ubuntu/Ubuntu-Italic.ttf
          style: italic
        - asset: assets/fonts/Ubuntu/Ubuntu-Light.ttf
          weight: 300
        - asset: assets/fonts/Ubuntu/Ubuntu-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Ubuntu/Ubuntu-Medium.ttf
          weight: 500
        - asset: assets/fonts/Ubuntu/Ubuntu-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Ubuntu/Ubuntu-Bold.ttf
          weight: 700
        - asset: assets/fonts/Ubuntu/Ubuntu-BoldItalic.ttf
          weight: 700
          style: italic

    - family: BeVietnam
      fonts:
        - asset: assets/fonts/Be_Vietnam/BeVietnam-Regular.ttf
        - asset: assets/fonts/Be_Vietnam/BeVietnam-Italic.ttf
          style: italic
        - asset: assets/fonts/Be_Vietnam/BeVietnam-Thin.ttf
          weight: 100
        - asset: assets/fonts/Be_Vietnam/BeVietnam-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Be_Vietnam/BeVietnam-Light.ttf
          weight: 300
        - asset: assets/fonts/Be_Vietnam/BeVietnam-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Be_Vietnam/BeVietnam-Medium.ttf
          weight: 500
        - asset: assets/fonts/Be_Vietnam/BeVietnam-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Be_Vietnam/BeVietnam-Bold.ttf
          weight: 700
        - asset: assets/fonts/Be_Vietnam/BeVietnam-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Be_Vietnam/BeVietnam-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Be_Vietnam/BeVietnam-ExtraBoldItalic.ttf
          weight: 800
          style: italic

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins/Poppins-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Poppins/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins/Poppins-BlackItalic.ttf
          weight: 900
          style: italic